### ISSUE TITLE
Update CONTRIBUTING.md file to include an example workflow

### ISSUE THREAD

**Issue by mbobra** [HelioML/HelioML#10]
Suggest the following workflow to contributors:

1. **Publish the code with yourself as first author.** The code could be published in a digital repository managed by an institutional library or Zenodo. Either way, generate a DOI for the code. 

2. **Publish the paper with yourself as first author, and include the link to the published code in the published paper.** This generates a separate DOI for the published paper (accepted papers are welcome too).

3. **Issue a PR to HelioML.** This way, HelioML is not showing anything for the first time. The contributors totally own the first publication of the code and the first publication of the paper.

**Comment by jmason86** [comment]
Merged and no lingering tasks. Think we're good to close this issue?
