### ISSUE TITLE
Update the table of contents with chapter 5 drill downs

### ISSUE THREAD

**Issue by jmason86** [HelioML/HelioML#15]
Now that chapter 5 is merged (check it out at [helioml.org](http://helioml.org)), I realize I need to update the drill down in Chapter 1 > In This Book.

**Comment by jmason86** [comment]
@rmcgranaghan can you take a look at how we structured things [here](http://helioml.org/01/2/in_this_book.html) and let me know how you'd follow that structure for your chapter, especially for the 
1. ML method(s) and concepts
2. Data source(s)

I have a start there for your chapter but wasn't able to quickly figure out what the data source drill down would be since I'm not as familiar with this field.

**Comment by rmcgranaghan** [comment]
Hi James

Fantastic work putting this together! Thanks for making the effort to have
this chapter included.

Are you interested in restructuring what is currently there? Would you
intent be to better align the text with the notebook evaluations? Just want
to understand what actions you would like me to take.

Thanks,
Ryan
*Ryan McGranaghan* - Aerospace Engineering Scientist | Principal Data
Scientist


          ASTRA, LLC

          282 Century Place, Suite 1000  |  Louisville, CO  80027
          Contact
          WeWork c/o Ryan McGranaghan, 641 S Street NW, Washington, DC 20001
          865.804.2169  |  ryan.mcgranaghan@gmail.com /
rmcgranaghan@astraspace.net |  astraspace.net

**Comment by jmason86** [comment]
Are there any other ML method(s) or concepts that should be included for the chapter? 

Under data source(s) we currently have: Solar wind, geomagnetic activity, particle precipitation, and ionospheric Global Navigation Satellite System (GNSS) data

But that should really be something like (making educated guesses here): 
* Solar wind > ion density > ACE/SWEPAM
* Geomagnetic activity > average equatorial horizontal component of Earth's magnetic field > Dst from NOAA 
* etc

**Comment by rmcgranaghan** [comment]
Hi James

Thanks for the input and my apologies for the slow response - June was a
heavy travel month. I hope you enjoyed a happy fourth and are in the midst
of an energizing weekend.

Here are my thoughts:

   - Data: in the paper for this material, we presented a table that
   covered the entirety of the data used. I modified it and am attaching a
   spreadsheet with a potential table for the HelioML chapter. What do you
   think?
   - ML methods: this work focused on SVM, but subsequent work has examine
   other approaches (e.g., random forests and neural networks). I suggest we
   could add a small block at the end with the following text and attached
   figure. Please let me know what you think.

SVMs have been examined in this chapter, however it is important to note
> that a massive space of ML approaches exist through which new scientific
> understanding can be created. We organize these methods across a spectrum
> of *explainability* - ranging from easily interpretable and interrogable
> (e.g., SVMs) to those that are more difficult to interrogate (e.g., deep
> neural networks). The examination of these methods need be accompanied by
> robust evaluation of the results using myriad metrics (e.g., *Bloomfield
> et al.*, 2012).
>

Thanks again for your suggestions and hard work. Very excited to have this
chapter in such good shape!

Regards,
Ryan

Bloomfield, D. S., Higgins, P. A., McAteer, R. T. J., & Gallagher, P. T.
(2012). Toward reliable benchmarking of solar flare forecasting methods.
The Astrophysical Journal Letters, 747(2), L41.

*Ryan McGranaghan* - Aerospace Engineering Scientist | Principal Data
Scientist


          ASTRA, LLC

          282 Century Place, Suite 1000  |  Louisville, CO  80027
          Contact
          WeWork c/o Ryan McGranaghan, 641 S Street NW, Washington, DC 20001
          865.804.2169  |  ryan.mcgranaghan@gmail.com /
rmcgranaghan@astraspace.net |  astraspace.net

**Comment by jmason86** [comment]
* Data: Van you attach the spreadsheet in the GitHub comment box? Because this conversation is mediated through the GitHub issue, I'm not able to get any attachments made directly in email. 
* ML methods: Your suggested additional text and figure in your chapter is fine by me, but not required. All I need for the [table of contents](http://helioml.org/01/2/in_this_book.html) is what's actually being demonstrated in the chapter itself. We have the support vector classifier listed ✅. If you look at the things we have listed for the other chapters in the table of contents, is there anything there or in that spirit that we should include for your chapter (e.g., data cleaning method, method for splitting data)? We'll only include things done in the chapter itself rather than anything that was done outside of it e.g., to prepare the data file that the chapter downloads from figshare.

**Comment by rmcgranaghan** [comment]
My apologies, the data spreadsheet is now attached here. 

With regard to the table of contents methods, I think perhaps the only other appropriate inclusion is the univariate feature selection algorithm that uses the Fisher ranking score for feature scoring. The reference we use is to Gu et al., [2011] (see below for full reference). It is a standard statistical analysis of variance (ANOVA) univariate F score test. 

Gu, Q., Li, Z., & Han, J. (2011). Generalized Fisher score for feature selection. In Proceedings of the Twenty-Seventh Conference on Uncertainty in Artificial Intelligence, UAI 11, AUAI Press, Arlington, Virginia, United States, pp. [266–273.]


[McGranaghan_DataTable.xlsx](https://github.com/HelioML/HelioML/files/3368949/McGranaghan_DataTable.xlsx)

**Comment by jmason86** [comment]
Perfect! I'll add this info to the table of contents. Thanks!

**Comment by jmason86** [comment]
Alright, I've made some progress -- I'm good on the ML methods but am stuck on the data. The spreadsheet lists the website from which the data were obtained, but not the observatory and instrument. Do you have that information?

**Comment by rmcgranaghan** [comment]
Hi James - sorry for my very tardy response (been a bit preoccupied with travel). 

I have attempted to capture the relevant information in this updated version of the data table. Please let me know if this is what you are looking for. In general, the observatory/instrument is difficult to specify for these data (the CHAIN network operates specific instruments, information about which have now been provided, but the CDAWeb data are compiled from multiple spacecraft and myriad instruments). 

[McGranaghan_DataTable.xlsx](https://github.com/HelioML/HelioML/files/3415015/McGranaghan_DataTable.xlsx)

**Comment by jmason86** [comment]
Nice, thanks!! I've used that to update the data sources in the table of contents. Check it out and let me know if anythings inaccurate or should be changed. It's chapter 5. 
http://helioml.org/table_of_contents.html

**Comment by rmcgranaghan** [comment]
Looks fantastic - thank you for the update! My only comment is with regard to - “” Kyoto WDCG

I assume the ` "" ' refers to the fact that this is the same as the line previous, but just wanted to double check. Is it worth writing out again (the other instruments explicitly write it out on each line)

Thanks again

**Comment by jmason86** [comment]
Good catch. In my head I'd replaced that but apparently that didn't happen in reality! It's updated now. Closing out this issue!
