### ISSUE TITLE
Problem importing Tensor flow in chapter 3

### ISSUE THREAD

**Issue by schonfsj** [HelioML/HelioML#35]
In the interactive version of Chapter 3, the third code cell that imports from keras and tensorflow gives the error `ModuleNotFoundError: No module named 'tensorflow'`. Additionally, if `import tensorflow as tf` is run by itself the same error is thrown. Obviously, this means none of the rest of the notebook can be executed.

**Comment by mbobra** [comment]
We decided to remove the interact button (PR #51 to address Issue #43), so this is no longer an issue.
