### ISSUE TITLE
Drop the Interact button

### ISSUE THREAD

**Issue by mbobra** [HelioML/HelioML#43]
👋 @PaulJWright @Brandonleighpanos @rmcgranaghan @cdiazbas 

@jmason86 and I are thinking of dropping the Interact button in the HelioML book. What do you think of this idea? 

Here are our reasons for dropping the button:

1. We secure the compute for this project via [Google Cloud Platform research credits](https://edu.google.com/programs/credits/research/?modal_active=none%3Fmodal_active%3DnoneBlogsocial&utm_campaign=2018-edu-gcp-research-credits). To date, GCP kindly gifted us up to six months of credits every time we applied. However, since this project doesn't have any funding, we ultimately depend on Google Cloud to bestow us with credits every six months. We have no way of buying credits if we fail to secure GCP research credits.
2. It is not actually feasible to do real analysis via the Binderhub interface (whether it is via our custom Binderhub or the free BinderHub). It would take an incredibly long time to run an entire notebook from start to finish multiple times, which is what it takes to tweak a machine learning model. Even if a user wanted to make a trivial change (say, change the cost function a little bit), it would take a lot of time and effort to run the whole notebook on the cloud, change one thing, and re-run through the notebook again. Also, users would lose all their changes as soon as they disconnect from BinderHub, forcing them to re-download all the input data if they want to re-connect at a later date.
3. As a result, we were thinking of asking contributors to make some kind of toy notebook for the book and link to the full notebook in the introduction or something. But this creates more work for contributors. Furthermore, they may not want to do it as creating a toy model will give poor results compared with using the full data set.
4. At some point, we're going to start running into problems with the environment file. Say I used scikit-learn version X and you used a newer version of the package, scikit-learn version Y. We don't necessarily want to run scikit-learn version Y on my notebook, because it may change my results. However, the jupyter-book infrastructure does not allow us to maintain multiple environment files.

These are all the reasons we think we should drop the Interact button. Instead, we can have a setup chapter telling users exactly how to run any given notebook on their local machine (or how to run it on some other cloud-based resource). Setup would basically consist of two steps:

Step 1: Create an environment, e.g.: `conda env create --file=myfile.yaml`

Step 2: Fire up Jupyter Lab, i.e.: `jupyter lab`

If we drop the Interact button, we don't have to rely on Google Cloud, users will not have to re-download data all the time and can run through the notebook multiple times pretty quickly (or much faster, to say the least), we don't have to ask contributors to do extra work, we can attach a different environment file to each notebook, and we don't have to spend so much time wrangling with Kubernetes.

What does everyone think?

**Comment by PaulJWright** [comment]
This sounds good! I agree.

**Comment by rmcgranaghan** [comment]
Thanks for laying out the case - I'm in agreement, too.

**Comment by Brandonleighpanos** [comment]
Hi Monica,

Sounds good to me too.

Cheers,
Brandon

**Comment by cdiazbas** [comment]
Hi Monica, I also agree! It sounds better. Cheers, Carlos.

**Comment by mbobra** [comment]
Addressed by #51
