### ISSUE TITLE
Redirect book to helioml.org

### ISSUE THREAD

**Issue by mbobra** [HelioML/HelioML#6]
The book should direct to helioml.org instead of the Github URL.
Add Google analytics to collect data on the traffic to the HelioML book ([steps here](https://jupyter.org/jupyter-book/guide/05_advanced.html)).

**Comment by PaulJWright** [comment]
In the process are you able to ensure that current links are preserved? E.g. https://helioml.github.io/HelioML/04/1/notebook

Thanks,
Paul

**Comment by jmason86** [comment]
I think so? I'll keep that in mind and work to make it happen.

**Comment by jmason86** [comment]
Alright, it's working! Links like the one @PaulJWright gave above still work: they do an automatic redirect. I'm going to mark this as done, but let me know if any issues come up and we can reopen. 

Check it out at [helioml.org](http://helioml.org).

**Comment by PaulJWright** [comment]
Great, thanks!

**Comment by mbobra** [comment]
Wow, this looks AWESOME 🔥🔥🔥 Nice work!!! 

Also thanks @ddasilva for all your good advice 👍

**Comment by ddasilva** [comment]
Great going guys!
