### ISSUE TITLE
Update the Whys and Whats section

### ISSUE THREAD

**Issue by mbobra** [HelioML/HelioML#8]
We should update the Why's and What's section to:

* Clearly state our main goal: The idea behind HelioML is to read a scientific paper and then, as a companion, visit the code to reproduce the results of the paper exactly. This has the secondary goal of teaching others about machine learning by example. The goal is to provide real world of examples of machine learning used in practice, not to teach the theory of machine learning.
* Put our lessons learned from talking about this back into the text.
* Add some text about the pros and cons of various learning algorithms and how one might go about choosing an algorithm for the task at hand.

It might be worthwhile to reference the following as well:
* A [Nature article by Monya Baker](http://adsabs.harvard.edu/abs/2016Natur.533..452B) showed that nearly 70% of research in physics and engineering isn't reproducible. More than 50% of researchers in this category can't even reproduce their own work. A third of labs across all scientific disciplines have no procedures for reproducibility. 
* [Jupyter notebooks](https://www.nature.com/articles/d41586-018-07196-1) [can help solve this problem](https://www.nature.com/news/interactive-notebooks-sharing-the-code-1.16261).
* The National Academy of Science, Engineering, and Medicine published a report on [Open Source Software Policy Options for NASA Earth and Space Sciences](https://doi.org/10.17226/25217), which included several options for open data and code policies.
* Some examples of open data and open code:
    * The Event Horizon Telescope data and VLBI image reconstruction code to generate the image of a black hole is [openly available](https://github.com/achael/eht-imaging). 
    * The LIGO data and analysis code to detect gravitational waves is [openly available](https://github.com/minrk/ligo-binder).

**Comment by jmason86** [comment]
I think the "Add some text about the pros and cons of various learning algorithms and how one might go about choosing an algorithm for the task at hand."  bullet belongs in the [In This Book](https://helioml.github.io/HelioML/01/2/in_this_book) section... no?

**Comment by jmason86** [comment]
I think the above commit closes the issue, assuming my earlier comment is correct. Feel free to reopen if not!
